export const GET_MEAL_BY_CATEGORY = "GET_MEAL_BY_CATEGORY";
export const GET_MEAL_BY_ID = "GET_MEAL_BY_ID";
export const GET_RANDOM_MEAL = "GET_RANDOM_MEAL";
export const ADD_MEAL_TO_FAVORITES = "ADD_MEAL_TO_FAVORITES";
export const REMOVE_MEAL_FROM_FAVORITES = "REMOVE_MEAL_FROM_FAVORITES";
